print("hello instagram")
print("\'hello instagram\'")
print("\"hello instagram\"")
print("hello\ninstagram")
print("hello\tinstagram")
print("hello\\instagram")
m = int(input("enter the number"))
n = int(input("enter the number"))
for i in range(n,m-1):
    print(i)
